name       : iso-codes
version    : 4.13.0
release    : 11
source     :
    - https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v4.13.0/iso-codes-v4.13.0.tar.bz2 : 99f85354b15061f5f8912d7fd70eb5eacfb31619c379d8cdeb23b5cede8e19db
license    : LGPL-2.1-only
component  : system.base
patterns   : /usr/share/pkgconfig
summary    : Central database of ISO codes
description: |
    The ISO Codes package contains a list of country, language and currency names and it is used as a central database for accessing this data.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
