name       : iso-codes
version    : 3.75
release    : 5
source     :
    - https://pkg-isocodes.alioth.debian.org/downloads/iso-codes-3.75.tar.xz : 7335e0301cd77cd4ee019bf5d3709aa79309d49dd66e85ba350caf67e00b00cd
license    : LGPL-2.1
component  : system.base
summary    : Central database of ISO codes
description: |
    The ISO Codes package contains a list of country, language and currency names and it is used as a central database for accessing this data.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
