name       : iso-codes
version    : 4.5.0
release    : 8
source     :
    - https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/iso-codes-4.5.0/iso-codes-iso-codes-4.5.0.tar.bz2 : 3e6d173aa15c708e677debed36687784652b74a9e4eed535f66b237c40f7d69e
license    : LGPL-2.1-only
component  : system.base
patterns   : /usr/share/pkgconfig
summary    : Central database of ISO codes
description: |
    The ISO Codes package contains a list of country, language and currency names and it is used as a central database for accessing this data.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
