name       : iso-codes
version    : '4.4'
release    : 7
source     :
    - https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/iso-codes-4.4/iso-codes-iso-codes-4.4.tar.bz2 : c676a78bb56b47638edbe0fc35570f88705e350f03e69adbac550d743ee3a00b
license    : LGPL-2.1-only
component  : system.base
patterns   : /usr/share/pkgconfig
summary    : Central database of ISO codes
description: |
    The ISO Codes package contains a list of country, language and currency names and it is used as a central database for accessing this data.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
